### ISSUE TITLE
Cant make Tx to Multiple Beneficiaries with separate IOTA values 

### ISSUE THREAD

**Issue by woywoy123** [iotaledger/iota.py#277]
Goal:
I want to be able to generate a multisignature bundle where I can specify different IOTA address beneficiaries with different iota payout values 

Example:
I have 3 beneficiaries: A1, A2, A3
I want to pay; A1(2i), A2(3i), A3(4i)

Observations: 
The following code sniplet works and passes bundle validation 

```py
api_1.prepare_multisig_transfer(
    transfers=[
        ProposedTransaction(
            address=Address(R1, R2, R3), 
            value = 2,
            message = "Hello World"
        )
    ], 
    multisig_input=multisig_address,
    change_address=None
)
```

The following change from above "value = [2,3,4]" doesn't work and returns an error. Same goes for "value= 2,3,4".

**Comment by lzpap** [comment]
Hi @woywoy123!

> I want to be able to generate a multisignature bundle where I can specify different IOTA address beneficiaries with different iota payout values

So if I get it right, you would like to create a bundle that pays out to 3 different addresses while the input transaction funding those txs is a multisig address?

If this is the case, simply create 3 output transactions with the 3 addresses and values in the bundle.

```
api_1.prepare_multisig_transfer(
  transfers=[
    ProposedTransaction(
      address=Address(R1),
      value = 2,
      message = "Hello World"
    ),
    ProposedTransaction(
      address=Address(R2),
      value = 3,
      message = "Hello World"
    ),
    ProposedTransaction(
      address=Address(R3),
      value = 4,
      message = "Hello World"
    ),
  ],
  multisig_input=multisig_address,
  change_address=None
)
```
By the way, if the input address has more funds than the sum of the outgoing transactions, it is strongly recommended to add a `change_address`, because the library can't automatically generate it for multisig input addresses.

A transaction may have only one address specified. Although it doesn't produce an error, creating an `Address` object like `Address(R1,R2,R3)` is semantically wrong. It will create an address that is essentially `R1`. Take a look at this small experiment:
```
>>> from iota import Address
>>> a1 = Address(b'FIRSTADDRESS')
>>> a2 = Address(b'SECONDADDRESS')
>>> a3 = Address(b'THIRDADDRESS')
>>> print(a1)
FIRSTADDRESS999999999999999999999999999999999999999999999999999999999999999999999
>>> print(a2)
SECONDADDRESS99999999999999999999999999999999999999999999999999999999999999999999
>>> print(a3)
THIRDADDRESS999999999999999999999999999999999999999999999999999999999999999999999
>>> combined = Address(a1,a2,a3)
>>> print(combined)
FIRSTADDRESS999999999999999999999999999999999999999999999999999999999999999999999
```

I hope this helps you to solve the problem! :)

**Comment by woywoy123** [comment]
This is exactly what I was looking for =) Thanks heaps!
