### ISSUE TITLE
Failing to import Private Signature key from string

### ISSUE THREAD

**Issue by woywoy123** [iotaledger/iota.py#278]
```py
from iota.crypto.types import PrivateKey
from iota.multisig import MultisigIota

Node = "http://localhost:14265"
Seed = "XXXX"

API = MultisigIota(adapter = Node, seed = Seed, local_pow = True)
Private_1 = API.get_private_keys(index = 1, count = 1, security_level = 3)["keys"][0]
Private_as_String = b'INSERT PRIV STRING'
Private_2 = PrivateKey(Private_as_String)
```

The error I am facing is that I cannot import a private key as string using the PrivateKey() function. Looking at the output of both Private_1 and Private_2 they produce the same output. I get the following error; 

```
Private.sign_input_transactions(Bundle_To_Sign, 1)
  File "/usr/local/lib/python3.7/dist-packages/iota/crypto/types.py", line 240, in sign_input_transactions
    for j in range(self.security_level):
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by lzpap** [comment]
Hi @woywoy123,
A `PrivateKey` object has two additional attributes (next to the actual tryte representation of the PK): `key_index` and `security_level`.

In your example, `Private_1` is generated with the API that fills these attributes, because it knows the parameters from the argument list.

When you import `Private_2` from a string, `PrivateKey` has no information about these two attributes, hence they are left empty, and that's why you get the `TypeError`.

Solution: Pass on theses argument when importing.
`PrivateKey(Private_as_string, index=***, security_level=***)`

Let me know if this worked :)

**Comment by woywoy123** [comment]
I just tried that and it worked!
